function [e11, e21, e22] = poly2S(f, g, h, s)
% POLY2S Calculate SRFT S-Parameters
%
% Calculates the S-parameters for a network generated by SRFT,
% represented by the h(s), f(s), and g(s) polynomials. Implements eq. 2,3
% in J+B. Note: e21 = e12, so only one is given.
%

	k = f.order();

	e11 = h.eval(s)./g.eval(s);
	e21 = f.eval(s)./g.eval(s);
	e22 = (-1).^(k+1) .* h.eval(s*-1)./g.eval(s);

end